services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ecommerce-giahuy-web:latest
    container_name: ecommerce-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:443"
    volumes:
      - ./docker/ssl:/etc/nginx/ssl:ro
      - ecommerce-shared-storage:/var/www/html/storage
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "true"
    networks:
      - ecommerce-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ecommerce-giahuy-web:latest
    container_name: ecommerce-worker
    restart: unless-stopped
    command: php artisan horizon
    env_file:
      - .env
    volumes:
      - ecommerce-shared-storage:/var/www/html/storage
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  ecommerce-shared-storage:
    driver: local