name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo ">>> Restarting Docker containers"
            docker compose down
            docker compose up -d --build

            cd /srv/web-host/www/app84/ecommerce
            git pull origin main
            
            chmod +x ./deploy.sh
            ./deploy.sh